version: '3.4'

services:
  chavahdbimporter:
    image: ${DOCKER_REGISTRY-}chavahdbimporter
    build:
      context: .
      dockerfile: src/ChavahDbImporter/Dockerfile
    ports:
      - "8080:8080"